---
title       : Interactive Documents with R
subtitle    : Slidify + Shiny
author      : Ramnath Vaidyanathan
job         : R Hacker
--- &radio

## Interactive Quiz

What is 1 + 1?

1. 1
2. _2_
3. 3
4. 4

*** .hint

This is a hint

*** .explanation

This is an explanation









---

## Interactive Chart

```{r echo = F, results = 'asis'}
require(rCharts)
haireye <- as.data.frame(HairEyeColor)
n1 <- nPlot(Freq ~ Eye, group = 'Hair', type = 'multiBarChart',
    data = subset(haireye, Sex == "Female")
)
n1$set(width = 800)
n1$print('chart1')
```















--- &interactive

## Interactive Console

```{r, opts.label = 'interactive', results = 'asis'}
require(googleVis)
M1 <- gvisMotionChart(Fruits, idvar = 'Fruit', timevar = 'Year')
print(M1, tag = 'chart')
```

---

## Non-Interactive Console

```{r, results = 'asis', comment = NA}
require(googleVis)
M1 <- gvisMotionChart(Fruits, idvar = 'Fruit', timevar = 'Year')
print(M1, tag = 'chart')
```


















---

## Interactive Chart with Shiny Controls

```{r opts.label = 'shiny'}
slidifyUI(
  sidebarPanel(
    selectInput('sex', 'Choose Sex', c('Male', 'Female')),
    selectInput('type', 'Choose Type', c('multiBarChart', 'multiBarHorizontalChart'))
  ),
  mainPanel(
    tags$div(id = 'nvd3plot', class='shiny-html-output nvd3 rChart')
  )
)
```














--- &interactive height:450

## Interactive Console 

```{r opts.label = 'interactive', results = 'asis'}
require(rCharts)
a <- Highcharts$new()
a$chart(type = "spline")
a$series(data = c(1, 3, 2, 4, 5, 4, 6, 2, 3, 5, NA), dashStyle = "longdash")
a$series(data = c(NA, 4, 1, 3, 4, 2, 9, 1, 2, 3, 4), dashStyle = "shortdot")
a$legend(symbolWidth = 80)
a$print('chart3')
```

--- &interactive height:450

```{r opts.label = 'interactive', results = 'asis'}
n1 <- nPlot(mpg ~ wt, 
  data = mtcars, 
  type = 'scatterChart', 
  group = 'gear'
)
n1$addControls("x", "wt", names(mtcars))
n1$set(width = 450, height = 350)
n1
```
















--- &interactive

## Results = Markup

```{r opts.label = 'interactive', results = 'markup'}
require(xtable)
options(xtable.type = 'html')
xtable(head(mtcars))
```























